"""empty message

Revision ID: 983357f6d639
Revises: 2de846ff02af
Create Date: 2020-10-20 01:40:47.146077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983357f6d639'
down_revision = '2de846ff02af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
